// Code generated by go-swagger; DO NOT EDIT.

package filters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFilterKeywordsGetParams creates a new FilterKeywordsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFilterKeywordsGetParams() *FilterKeywordsGetParams {
	return &FilterKeywordsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFilterKeywordsGetParamsWithTimeout creates a new FilterKeywordsGetParams object
// with the ability to set a timeout on a request.
func NewFilterKeywordsGetParamsWithTimeout(timeout time.Duration) *FilterKeywordsGetParams {
	return &FilterKeywordsGetParams{
		timeout: timeout,
	}
}

// NewFilterKeywordsGetParamsWithContext creates a new FilterKeywordsGetParams object
// with the ability to set a context for a request.
func NewFilterKeywordsGetParamsWithContext(ctx context.Context) *FilterKeywordsGetParams {
	return &FilterKeywordsGetParams{
		Context: ctx,
	}
}

// NewFilterKeywordsGetParamsWithHTTPClient creates a new FilterKeywordsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewFilterKeywordsGetParamsWithHTTPClient(client *http.Client) *FilterKeywordsGetParams {
	return &FilterKeywordsGetParams{
		HTTPClient: client,
	}
}

/*
FilterKeywordsGetParams contains all the parameters to send to the API endpoint

	for the filter keywords get operation.

	Typically these are written to a http.Request.
*/
type FilterKeywordsGetParams struct {

	/* ID.

	   ID of the filter
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the filter keywords get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FilterKeywordsGetParams) WithDefaults() *FilterKeywordsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the filter keywords get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FilterKeywordsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the filter keywords get params
func (o *FilterKeywordsGetParams) WithTimeout(timeout time.Duration) *FilterKeywordsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the filter keywords get params
func (o *FilterKeywordsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the filter keywords get params
func (o *FilterKeywordsGetParams) WithContext(ctx context.Context) *FilterKeywordsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the filter keywords get params
func (o *FilterKeywordsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the filter keywords get params
func (o *FilterKeywordsGetParams) WithHTTPClient(client *http.Client) *FilterKeywordsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the filter keywords get params
func (o *FilterKeywordsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the filter keywords get params
func (o *FilterKeywordsGetParams) WithID(id string) *FilterKeywordsGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the filter keywords get params
func (o *FilterKeywordsGetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FilterKeywordsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
