// Code generated by go-swagger; DO NOT EDIT.

package interaction_requests

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/VyrCossont/slurp/models"
)

// RejectInteractionRequestReader is a Reader for the RejectInteractionRequest structure.
type RejectInteractionRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RejectInteractionRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRejectInteractionRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRejectInteractionRequestBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewRejectInteractionRequestUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRejectInteractionRequestNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 406:
		result := NewRejectInteractionRequestNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRejectInteractionRequestInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/interaction_requests/{id}/reject] rejectInteractionRequest", response, response.Code())
	}
}

// NewRejectInteractionRequestOK creates a RejectInteractionRequestOK with default headers values
func NewRejectInteractionRequestOK() *RejectInteractionRequestOK {
	return &RejectInteractionRequestOK{}
}

/*
RejectInteractionRequestOK describes a response with status code 200, with default header values.

The now-rejected interaction request.
*/
type RejectInteractionRequestOK struct {
	Payload *models.InteractionRequest
}

// IsSuccess returns true when this reject interaction request o k response has a 2xx status code
func (o *RejectInteractionRequestOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this reject interaction request o k response has a 3xx status code
func (o *RejectInteractionRequestOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reject interaction request o k response has a 4xx status code
func (o *RejectInteractionRequestOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this reject interaction request o k response has a 5xx status code
func (o *RejectInteractionRequestOK) IsServerError() bool {
	return false
}

// IsCode returns true when this reject interaction request o k response a status code equal to that given
func (o *RejectInteractionRequestOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the reject interaction request o k response
func (o *RejectInteractionRequestOK) Code() int {
	return 200
}

func (o *RejectInteractionRequestOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/interaction_requests/{id}/reject][%d] rejectInteractionRequestOK %s", 200, payload)
}

func (o *RejectInteractionRequestOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/interaction_requests/{id}/reject][%d] rejectInteractionRequestOK %s", 200, payload)
}

func (o *RejectInteractionRequestOK) GetPayload() *models.InteractionRequest {
	return o.Payload
}

func (o *RejectInteractionRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InteractionRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRejectInteractionRequestBadRequest creates a RejectInteractionRequestBadRequest with default headers values
func NewRejectInteractionRequestBadRequest() *RejectInteractionRequestBadRequest {
	return &RejectInteractionRequestBadRequest{}
}

/*
RejectInteractionRequestBadRequest describes a response with status code 400, with default header values.

bad request
*/
type RejectInteractionRequestBadRequest struct {
}

// IsSuccess returns true when this reject interaction request bad request response has a 2xx status code
func (o *RejectInteractionRequestBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this reject interaction request bad request response has a 3xx status code
func (o *RejectInteractionRequestBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reject interaction request bad request response has a 4xx status code
func (o *RejectInteractionRequestBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this reject interaction request bad request response has a 5xx status code
func (o *RejectInteractionRequestBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this reject interaction request bad request response a status code equal to that given
func (o *RejectInteractionRequestBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the reject interaction request bad request response
func (o *RejectInteractionRequestBadRequest) Code() int {
	return 400
}

func (o *RejectInteractionRequestBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v1/interaction_requests/{id}/reject][%d] rejectInteractionRequestBadRequest", 400)
}

func (o *RejectInteractionRequestBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v1/interaction_requests/{id}/reject][%d] rejectInteractionRequestBadRequest", 400)
}

func (o *RejectInteractionRequestBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRejectInteractionRequestUnauthorized creates a RejectInteractionRequestUnauthorized with default headers values
func NewRejectInteractionRequestUnauthorized() *RejectInteractionRequestUnauthorized {
	return &RejectInteractionRequestUnauthorized{}
}

/*
RejectInteractionRequestUnauthorized describes a response with status code 401, with default header values.

unauthorized
*/
type RejectInteractionRequestUnauthorized struct {
}

// IsSuccess returns true when this reject interaction request unauthorized response has a 2xx status code
func (o *RejectInteractionRequestUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this reject interaction request unauthorized response has a 3xx status code
func (o *RejectInteractionRequestUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reject interaction request unauthorized response has a 4xx status code
func (o *RejectInteractionRequestUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this reject interaction request unauthorized response has a 5xx status code
func (o *RejectInteractionRequestUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this reject interaction request unauthorized response a status code equal to that given
func (o *RejectInteractionRequestUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the reject interaction request unauthorized response
func (o *RejectInteractionRequestUnauthorized) Code() int {
	return 401
}

func (o *RejectInteractionRequestUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1/interaction_requests/{id}/reject][%d] rejectInteractionRequestUnauthorized", 401)
}

func (o *RejectInteractionRequestUnauthorized) String() string {
	return fmt.Sprintf("[POST /api/v1/interaction_requests/{id}/reject][%d] rejectInteractionRequestUnauthorized", 401)
}

func (o *RejectInteractionRequestUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRejectInteractionRequestNotFound creates a RejectInteractionRequestNotFound with default headers values
func NewRejectInteractionRequestNotFound() *RejectInteractionRequestNotFound {
	return &RejectInteractionRequestNotFound{}
}

/*
RejectInteractionRequestNotFound describes a response with status code 404, with default header values.

not found
*/
type RejectInteractionRequestNotFound struct {
}

// IsSuccess returns true when this reject interaction request not found response has a 2xx status code
func (o *RejectInteractionRequestNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this reject interaction request not found response has a 3xx status code
func (o *RejectInteractionRequestNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reject interaction request not found response has a 4xx status code
func (o *RejectInteractionRequestNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this reject interaction request not found response has a 5xx status code
func (o *RejectInteractionRequestNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this reject interaction request not found response a status code equal to that given
func (o *RejectInteractionRequestNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the reject interaction request not found response
func (o *RejectInteractionRequestNotFound) Code() int {
	return 404
}

func (o *RejectInteractionRequestNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1/interaction_requests/{id}/reject][%d] rejectInteractionRequestNotFound", 404)
}

func (o *RejectInteractionRequestNotFound) String() string {
	return fmt.Sprintf("[POST /api/v1/interaction_requests/{id}/reject][%d] rejectInteractionRequestNotFound", 404)
}

func (o *RejectInteractionRequestNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRejectInteractionRequestNotAcceptable creates a RejectInteractionRequestNotAcceptable with default headers values
func NewRejectInteractionRequestNotAcceptable() *RejectInteractionRequestNotAcceptable {
	return &RejectInteractionRequestNotAcceptable{}
}

/*
RejectInteractionRequestNotAcceptable describes a response with status code 406, with default header values.

not acceptable
*/
type RejectInteractionRequestNotAcceptable struct {
}

// IsSuccess returns true when this reject interaction request not acceptable response has a 2xx status code
func (o *RejectInteractionRequestNotAcceptable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this reject interaction request not acceptable response has a 3xx status code
func (o *RejectInteractionRequestNotAcceptable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reject interaction request not acceptable response has a 4xx status code
func (o *RejectInteractionRequestNotAcceptable) IsClientError() bool {
	return true
}

// IsServerError returns true when this reject interaction request not acceptable response has a 5xx status code
func (o *RejectInteractionRequestNotAcceptable) IsServerError() bool {
	return false
}

// IsCode returns true when this reject interaction request not acceptable response a status code equal to that given
func (o *RejectInteractionRequestNotAcceptable) IsCode(code int) bool {
	return code == 406
}

// Code gets the status code for the reject interaction request not acceptable response
func (o *RejectInteractionRequestNotAcceptable) Code() int {
	return 406
}

func (o *RejectInteractionRequestNotAcceptable) Error() string {
	return fmt.Sprintf("[POST /api/v1/interaction_requests/{id}/reject][%d] rejectInteractionRequestNotAcceptable", 406)
}

func (o *RejectInteractionRequestNotAcceptable) String() string {
	return fmt.Sprintf("[POST /api/v1/interaction_requests/{id}/reject][%d] rejectInteractionRequestNotAcceptable", 406)
}

func (o *RejectInteractionRequestNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRejectInteractionRequestInternalServerError creates a RejectInteractionRequestInternalServerError with default headers values
func NewRejectInteractionRequestInternalServerError() *RejectInteractionRequestInternalServerError {
	return &RejectInteractionRequestInternalServerError{}
}

/*
RejectInteractionRequestInternalServerError describes a response with status code 500, with default header values.

internal server error
*/
type RejectInteractionRequestInternalServerError struct {
}

// IsSuccess returns true when this reject interaction request internal server error response has a 2xx status code
func (o *RejectInteractionRequestInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this reject interaction request internal server error response has a 3xx status code
func (o *RejectInteractionRequestInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reject interaction request internal server error response has a 4xx status code
func (o *RejectInteractionRequestInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this reject interaction request internal server error response has a 5xx status code
func (o *RejectInteractionRequestInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this reject interaction request internal server error response a status code equal to that given
func (o *RejectInteractionRequestInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the reject interaction request internal server error response
func (o *RejectInteractionRequestInternalServerError) Code() int {
	return 500
}

func (o *RejectInteractionRequestInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/interaction_requests/{id}/reject][%d] rejectInteractionRequestInternalServerError", 500)
}

func (o *RejectInteractionRequestInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v1/interaction_requests/{id}/reject][%d] rejectInteractionRequestInternalServerError", 500)
}

func (o *RejectInteractionRequestInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
