// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHeaderFilterAllowsGetParams creates a new HeaderFilterAllowsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHeaderFilterAllowsGetParams() *HeaderFilterAllowsGetParams {
	return &HeaderFilterAllowsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHeaderFilterAllowsGetParamsWithTimeout creates a new HeaderFilterAllowsGetParams object
// with the ability to set a timeout on a request.
func NewHeaderFilterAllowsGetParamsWithTimeout(timeout time.Duration) *HeaderFilterAllowsGetParams {
	return &HeaderFilterAllowsGetParams{
		timeout: timeout,
	}
}

// NewHeaderFilterAllowsGetParamsWithContext creates a new HeaderFilterAllowsGetParams object
// with the ability to set a context for a request.
func NewHeaderFilterAllowsGetParamsWithContext(ctx context.Context) *HeaderFilterAllowsGetParams {
	return &HeaderFilterAllowsGetParams{
		Context: ctx,
	}
}

// NewHeaderFilterAllowsGetParamsWithHTTPClient creates a new HeaderFilterAllowsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewHeaderFilterAllowsGetParamsWithHTTPClient(client *http.Client) *HeaderFilterAllowsGetParams {
	return &HeaderFilterAllowsGetParams{
		HTTPClient: client,
	}
}

/*
HeaderFilterAllowsGetParams contains all the parameters to send to the API endpoint

	for the header filter allows get operation.

	Typically these are written to a http.Request.
*/
type HeaderFilterAllowsGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the header filter allows get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HeaderFilterAllowsGetParams) WithDefaults() *HeaderFilterAllowsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the header filter allows get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HeaderFilterAllowsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the header filter allows get params
func (o *HeaderFilterAllowsGetParams) WithTimeout(timeout time.Duration) *HeaderFilterAllowsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the header filter allows get params
func (o *HeaderFilterAllowsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the header filter allows get params
func (o *HeaderFilterAllowsGetParams) WithContext(ctx context.Context) *HeaderFilterAllowsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the header filter allows get params
func (o *HeaderFilterAllowsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the header filter allows get params
func (o *HeaderFilterAllowsGetParams) WithHTTPClient(client *http.Client) *HeaderFilterAllowsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the header filter allows get params
func (o *HeaderFilterAllowsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *HeaderFilterAllowsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
