// Code generated by go-swagger; DO NOT EDIT.

package nodeinfo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewNodeInfoGetParams creates a new NodeInfoGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNodeInfoGetParams() *NodeInfoGetParams {
	return &NodeInfoGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNodeInfoGetParamsWithTimeout creates a new NodeInfoGetParams object
// with the ability to set a timeout on a request.
func NewNodeInfoGetParamsWithTimeout(timeout time.Duration) *NodeInfoGetParams {
	return &NodeInfoGetParams{
		timeout: timeout,
	}
}

// NewNodeInfoGetParamsWithContext creates a new NodeInfoGetParams object
// with the ability to set a context for a request.
func NewNodeInfoGetParamsWithContext(ctx context.Context) *NodeInfoGetParams {
	return &NodeInfoGetParams{
		Context: ctx,
	}
}

// NewNodeInfoGetParamsWithHTTPClient creates a new NodeInfoGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewNodeInfoGetParamsWithHTTPClient(client *http.Client) *NodeInfoGetParams {
	return &NodeInfoGetParams{
		HTTPClient: client,
	}
}

/*
NodeInfoGetParams contains all the parameters to send to the API endpoint

	for the node info get operation.

	Typically these are written to a http.Request.
*/
type NodeInfoGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the node info get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NodeInfoGetParams) WithDefaults() *NodeInfoGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the node info get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NodeInfoGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the node info get params
func (o *NodeInfoGetParams) WithTimeout(timeout time.Duration) *NodeInfoGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the node info get params
func (o *NodeInfoGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the node info get params
func (o *NodeInfoGetParams) WithContext(ctx context.Context) *NodeInfoGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the node info get params
func (o *NodeInfoGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the node info get params
func (o *NodeInfoGetParams) WithHTTPClient(client *http.Client) *NodeInfoGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the node info get params
func (o *NodeInfoGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *NodeInfoGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
