// Code generated by go-swagger; DO NOT EDIT.

package nodeinfo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/VyrCossont/slurp/models"
)

// NodeInfoGetReader is a Reader for the NodeInfoGet structure.
type NodeInfoGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NodeInfoGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNodeInfoGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /nodeinfo/2.0] nodeInfoGet", response, response.Code())
	}
}

// NewNodeInfoGetOK creates a NodeInfoGetOK with default headers values
func NewNodeInfoGetOK() *NodeInfoGetOK {
	return &NodeInfoGetOK{}
}

/*
NodeInfoGetOK describes a response with status code 200, with default header values.

NodeInfoGetOK node info get o k
*/
type NodeInfoGetOK struct {
	Payload *models.Nodeinfo
}

// IsSuccess returns true when this node info get o k response has a 2xx status code
func (o *NodeInfoGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this node info get o k response has a 3xx status code
func (o *NodeInfoGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this node info get o k response has a 4xx status code
func (o *NodeInfoGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this node info get o k response has a 5xx status code
func (o *NodeInfoGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this node info get o k response a status code equal to that given
func (o *NodeInfoGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the node info get o k response
func (o *NodeInfoGetOK) Code() int {
	return 200
}

func (o *NodeInfoGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nodeinfo/2.0][%d] nodeInfoGetOK %s", 200, payload)
}

func (o *NodeInfoGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /nodeinfo/2.0][%d] nodeInfoGetOK %s", 200, payload)
}

func (o *NodeInfoGetOK) GetPayload() *models.Nodeinfo {
	return o.Payload
}

func (o *NodeInfoGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Nodeinfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
