// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAccountsFeaturedTagsParams creates a new AccountsFeaturedTagsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAccountsFeaturedTagsParams() *AccountsFeaturedTagsParams {
	return &AccountsFeaturedTagsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAccountsFeaturedTagsParamsWithTimeout creates a new AccountsFeaturedTagsParams object
// with the ability to set a timeout on a request.
func NewAccountsFeaturedTagsParamsWithTimeout(timeout time.Duration) *AccountsFeaturedTagsParams {
	return &AccountsFeaturedTagsParams{
		timeout: timeout,
	}
}

// NewAccountsFeaturedTagsParamsWithContext creates a new AccountsFeaturedTagsParams object
// with the ability to set a context for a request.
func NewAccountsFeaturedTagsParamsWithContext(ctx context.Context) *AccountsFeaturedTagsParams {
	return &AccountsFeaturedTagsParams{
		Context: ctx,
	}
}

// NewAccountsFeaturedTagsParamsWithHTTPClient creates a new AccountsFeaturedTagsParams object
// with the ability to set a custom HTTPClient for a request.
func NewAccountsFeaturedTagsParamsWithHTTPClient(client *http.Client) *AccountsFeaturedTagsParams {
	return &AccountsFeaturedTagsParams{
		HTTPClient: client,
	}
}

/*
AccountsFeaturedTagsParams contains all the parameters to send to the API endpoint

	for the accounts featured tags operation.

	Typically these are written to a http.Request.
*/
type AccountsFeaturedTagsParams struct {

	/* ID.

	   The id of the account.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the accounts featured tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AccountsFeaturedTagsParams) WithDefaults() *AccountsFeaturedTagsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the accounts featured tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AccountsFeaturedTagsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the accounts featured tags params
func (o *AccountsFeaturedTagsParams) WithTimeout(timeout time.Duration) *AccountsFeaturedTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the accounts featured tags params
func (o *AccountsFeaturedTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the accounts featured tags params
func (o *AccountsFeaturedTagsParams) WithContext(ctx context.Context) *AccountsFeaturedTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the accounts featured tags params
func (o *AccountsFeaturedTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the accounts featured tags params
func (o *AccountsFeaturedTagsParams) WithHTTPClient(client *http.Client) *AccountsFeaturedTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the accounts featured tags params
func (o *AccountsFeaturedTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the accounts featured tags params
func (o *AccountsFeaturedTagsParams) WithID(id string) *AccountsFeaturedTagsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the accounts featured tags params
func (o *AccountsFeaturedTagsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *AccountsFeaturedTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
