// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// FilterAction FilterAction is the action to apply to statuses matching a filter.
//
// swagger:model FilterAction
type FilterAction string

// Validate validates this filter action
func (m FilterAction) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this filter action based on context it is used
func (m FilterAction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
