// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InstanceV2ConfigurationTranslation Hints related to translation.
//
// swagger:model InstanceV2ConfigurationTranslation
type InstanceV2ConfigurationTranslation struct {

	// Whether the Translations API is available on this instance.
	// Not implemented so this value is always false.
	Enabled bool `json:"enabled,omitempty"`
}

// Validate validates this instance v2 configuration translation
func (m *InstanceV2ConfigurationTranslation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this instance v2 configuration translation based on context it is used
func (m *InstanceV2ConfigurationTranslation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InstanceV2ConfigurationTranslation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InstanceV2ConfigurationTranslation) UnmarshalBinary(b []byte) error {
	var res InstanceV2ConfigurationTranslation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
