// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateField UpdateField is to be used specifically in an UpdateCredentialsRequest.
//
// By default, max 6 fields and 255 characters per property/value.
//
// swagger:model UpdateField
type UpdateField struct {

	// Name of the field
	Name string `json:"name,omitempty"`

	// Value of the field
	Value string `json:"value,omitempty"`
}

// Validate validates this update field
func (m *UpdateField) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update field based on context it is used
func (m *UpdateField) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateField) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateField) UnmarshalBinary(b []byte) error {
	var res UpdateField
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
